name: CI

on:
  pull_request:
  push:
    branches: [$default-branch]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: r7kamura/rust-problem-matchers@v1
      - uses: actions/checkout@v4
      - run: cargo fmt --check

  check:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: r7kamura/rust-problem-matchers@v1
      - uses: actions/checkout@v4
      - run: cargo check --workspace --all-targets --all-features

  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: r7kamura/rust-problem-matchers@v1
      - uses: actions/checkout@v4
      - run: cargo clippy --workspace --all-targets --all-features

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - 1.85.0 # MSRV
          - stable
          - beta
          - nightly
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: r7kamura/rust-problem-matchers@v1
      - uses: actions/checkout@v4
      - run: cargo test --workspace --all-features

  semver-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
